services:
  console_app:
    image: php_prod
    build: # we are specifying the version in the Dockerfile
      target: php_prod
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/swarmdeploy
    working_dir: /srv/swarmdeploy
    ports:
      - "8000:8000"

  webserver:
    depends_on:
      - console_app
    image: caddy:2.7.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/config:/config
      - .:/srv/ioda