services:
  console_app:
    container_name: ioda_php
    depends_on:
      - luceneparser
    build: # we are specifying the version in the Dockerfile
      target: php_dev
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/srv/ioda
      - ./vendor:/srv/ioda/vendor
    working_dir: /srv/ioda
    ports:
      - "8000:8000"

  webserver:
    depends_on:
      - console_app
    image: caddy:2.7.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./docker/caddy/config:/config
      - .:/srv/ioda